/**
 * Generated by giftwrap
 */
package ${package};

public final class ${name} implements ${super} {

<#list properties as property>
    private ${property.type} ${property.name}<#if property.defaultValue?? > = ${property.defaultValue}</#if>;

</#list>
<#list properties as property>
    public ${property.type} ${property.name}() {
        return this.${property.name};
    }
    
    public void ${property.name}(${property.type} ${property.name}) {
        this.${property.name} = ${property.name};
    }
    
</#list>
    public Class<${super}> annotationType() {
        return ${super}.class;
    }
    
}
